import Image from 'next/image';

import Page from 'components/page';

import Applause from 'assets/acknowledging-applause.jpg';
import Gala13 from 'assets/gala-13-setting-show-from-far-away.jpg';
import Gala14 from 'assets/gala-14.jpg';
import Gala9 from 'assets/gala-9-robin-and-michael.jpg';
import GalaPointingUp from 'assets/gala-10-pointing-up.jpg';

export default function Home(): JSX.Element {
  return (
    <Page name='Home' header={false}>
      <main>
        <section className='hero dark'>
          <div className='images'>
            {[Gala9, Gala13, GalaPointingUp, Applause, Gala14].map((img) => (
              <Image
                alt=''
                src={img}
                key={img.src}
                placeholder='blur'
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                priority
              />
            ))}
          </div>
          <div className='scrim' />
          <header>
            <h1>
              Saint
              <br />
              Michael
              <br />
              Trio
            </h1>
            <h2>
              Silicon Valley’s update to
              <br />
              the classical music scene
            </h2>
            <h3>
              Robin Sharp, violin; Russell Hancock, piano; Michel Flexer, cello
            </h3>
          </header>
        </section>
      </main>
      <style jsx>{`
        section.hero {
          position: relative;
          background-color: var(--background);
          padding: 0;
          margin: 0;
          min-height: 100vh;
          margin-bottom: -2rem;
          width: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .scrim {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.25);
        }

        section.hero header {
          position: relative;
          max-width: calc(var(--page-width) + 2 * 24px);
          width: 100%;
          padding: 0 24px;
          margin: 2rem auto;
        }

        section.hero h1 {
          font-size: 6rem;
          font-weight: 900;
          letter-spacing: -0.25rem;
          text-transform: uppercase;
          line-height: 0.85;
          margin: 3rem 0;
          font-family: var(--font-sans);
          color: var(--on-background);
          animation-duration: 1s;
          animation-name: fade;
          animation-fill-mode: both;
        }

        section.hero h2 {
          font-size: 2rem;
          font-weight: 700;
          line-height: 1.2;
          letter-spacing: -0.05rem;
          margin: 3rem 0 1rem;
          color: var(--on-background);
          font-family: var(--font-sans);
          animation-delay: 0.2s;
          animation-duration: 1s;
          animation-name: fade;
          animation-fill-mode: both;
        }

        section.hero h3 {
          font-size: 0.8rem;
          font-weight: 700;
          line-height: 1.2;
          margin: 1rem 0 3rem;
          color: var(--on-background);
          font-family: var(--font-sans);
          animation-delay: 0.2s;
          animation-duration: 1s;
          animation-name: fade;
          animation-fill-mode: both;
        }

        @keyframes fade {
          from {
            opacity: 0;
            transform: translate(0, 0.85rem);
          }
          to {
            opacity: 1;
            transform: translate(0, 0);
          }
        }

        .images {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
        }

        /* Generated by: https://codepen.io/andreasfurster/pen/QWKWNGe */

        .images > :global(div:nth-child(1)) {
          animation: fadeinout 20s linear -0.8s infinite;
        }

        .images > :global(div:nth-child(2)) {
          animation: fadeinout 20s linear 3.2s infinite;
        }

        .images > :global(div:nth-child(3)) {
          animation: fadeinout 20s linear 7.2s infinite;
        }

        .images > :global(div:nth-child(4)) {
          animation: fadeinout 20s linear 11.2s infinite;
        }

        .images > :global(div:nth-child(5)) {
          animation: fadeinout 20s linear 15.2s infinite;
        }

        @keyframes fadeinout {
          0% {
            opacity: 0;
          }
          4%,
          20% {
            opacity: 1;
          }
          24%,
          100% {
            opacity: 0;
          }
        }
      `}</style>
    </Page>
  );
}
